# Generated by Django 5.1.4 on 2024-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
            ],
        ),
    ]
